### ISSUE TITLE
Compile error "conflicting types for 'write_out_fpocket_info_file'"

### ISSUE THREAD

**Issue by harryjubb** [Discngine/fpocket#5]
Hi,

Great to see fPocket on GitHub 😃 

I'm trying to compile on OS X 10.11.6 and am getting an error.

I changed `ARCH` to `MACOSX` in the makefile before running `make`.

GCC version:
```
$ gcc -v                                                                                        
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The full make output is here:
[make.error.txt](https://github.com/Discngine/fpocket/files/1957844/make.error.txt)

I found this can be fixed by adding

    void write_out_fpocket_info_file(c_lst_pockets *pockets, char *output_file_name);

to `headers/fpout.h`.

If this error isn't isolated to my setup, I can make a pull request with this fix.

I got further errors after fixing this one, but I can make separate issues for those.

**Comment by pschmidtke** [comment]
Hey, thanks for pointing those out. I'm on travel right now so cannot check until mid next week. However didn't manage to compile yet fully (mdpocket) on osx as mdpocket has now a dependency to the vmd molfile plugin and this one is rather difficult to compile. I'll check out all the issues you posted. Help is very much appreciated and nice to see that the move to github is already useful ;)

Anyway as for now still only Linux supported. Any interest in a docker container BTW?

Cheers

**Comment by harryjubb** [comment]
No problem, I'm keen to try out the updated version. That makes sense, most things I'd run on Linux but for quick things it's nice having it on Mac.

Definitely interested in a Docker container! I dockerised fpocket2 a while ago (more for curiosity than anything), it was very straightforward, I'm happy to share the Dockerfile. For 3.* I imagine it's more involved, I'll have a go at compiling it on Linux when I next have a chance.

**Comment by pschmidtke** [comment]
Ok I looked into it. Seems like I'm using a macports gcc instead and this seems to work quite OK (a part from netcdf support not yet OK). On my side the whole thing compiles through. I added the missing function definition, but the macports gcc version I have seems more permissive than clang you use. 
Is installing gcc with macports an option for you? :) 

Here are my details : 
Mac-Pro:fpocket peter$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin16/4.9.4/lto-wrapper
Target: x86_64-apple-darwin16
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc49/gcc49/work/gcc-4.9.4/configure --prefix=/opt/local --build=x86_64-apple-darwin16 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc49 --includedir=/opt/local/include/gcc49 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.9 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.9 --with-gxx-include-dir=/opt/local/include/gcc49/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=b

On OSX 10.12.6

**Comment by pschmidtke** [comment]
don't hesitate to propose PR's, i'll double check and integrate them

**Comment by harryjubb** [comment]
Thanks for your reply, sadly I'm on a managed laptop, though I do have homebrew installed. I'm always a bit terrified to mess with gcc 😄 but can see if I can try with the brew gcc.

**Comment by pschmidtke** [comment]
fpocket should support clang fully now. I tested on my OSX but as I also have gcc lying around you never can be sure 100% :) so please test if you have 5mn and are still interested in having a full mac version of fpocket.
